#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
  namespace: kv-frontend-apps
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:latest
        volumeMounts:
          - name: my-tomcat-volume
            subPath: "webapps"
            mountPath: "/usr/local/tomcat/webapps"
          - name: my-tomcat-volume
            subPath: "config" ## Config to enable Tomcat on port 80 if needed
            mountPath: "/usr/local/tomcat/conf"            
      volumes:
        - name: my-tomcat-volume
          persistentVolumeClaim:
            claimName: tomcat-pvc
        
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  namespace: kv-frontend-apps
spec:
  selector:
    app: tomcat
  ports:
    - name: tomcat
      protocol: TCP
      port: 8080
      targetPort: 8080

---
## Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tomcat-ingress
  namespace: kv-frontend-apps
spec:
  ingressClassName: nginx
  rules:
  - host: kvhome.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tomcat-svc
            port:
              number: 8080