apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  labels:
    type: local
spec:
  storageClassName: pihole-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/pool_500_860evo/app-data/pihole"