## Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  labels:
    app: config-server
  namespace: kv-backend-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: kaivalya461/config-server
        envFrom:
        - secretRef:
            name: config-server-secret
---
## Service       
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  namespace: kv-backend-apps
spec:
  selector:
    app: config-server
  # type: LoadBalancer
  ports:
    - name: config-server
      protocol: TCP
      port: 8888
      targetPort: 8888
      # nodePort: 30030


---
## Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: config-server-ingress
  namespace: kv-backend-apps
spec:
  ingressClassName: nginx
  rules:
  - host: config-server.kvhome.in
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: config-server-service
            port:
              number: 8888