## PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wicked-fast-jenkins-agent-pvc
  namespace: kv-devops-tools
spec:
  storageClassName: wicked-fast-jenkins-agent-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi