apiVersion: v1
kind: PersistentVolume
metadata:
  name: wicked-fast-jenkins-agent-pv
  labels:
    type: local
spec:
  storageClassName: wicked-fast-jenkins-agent-data
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    ## Update below path with appropriate host path ##
    
    # Linux Path
    # path: "/home/pvtest"

    # Truenas Dataset
    path: "/mnt/pool_500_860evo/app-data/wicked-fast-jenkins-agent"

    # Windows Path
    # path: "F:\\DatabaseStorage\\KubernetesPVData\\postgres-pv"
