apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: kv-devops-tools
spec:
  storageClassName: jenkins-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi