apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    type: local
spec:
  storageClassName: jenkins-data
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    # Update below path with appropriate host path
    path: "/mnt/pool_500_860evo/app-data/jenkins-app"
    # Truenas Dataset
    # /mnt/pool_32_gig/truenas-docker-apps/DockerDataVolume