apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-apps-volume
  labels:
    type: local
spec:
  storageClassName: docker-data
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # Update below path with appropriate host path
    path: "/home/pvtest"
    # Truenas Dataset
    # /mnt/pool_32_gig/truenas-docker-apps/DockerDataVolume