## Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shwish-wish-deployment
  labels:
    app: shwish-wish
  namespace: kv-backend-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shwish-wish
  template:
    metadata:
      labels:
        app: shwish-wish
    spec:
      containers:
      - name: shwish-wish
        image: kaivalya461/shwish-wish
        # envFrom:
        # - secretRef:
        #     name: config-server-secret
---
## Service       
apiVersion: v1
kind: Service
metadata:
  name: shwish-wish-service
  namespace: kv-backend-apps
spec:
  selector:
    app: shwish-wish
  # type: LoadBalancer
  ports:
    - name: shwish-wish
      protocol: TCP
      port: 8080
      targetPort: 8080


---
## Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: shwish-wish-ingress
  namespace: kv-backend-apps
spec:
  ingressClassName: nginx
  rules:
  - host: kvhome.in
    http:
      paths:
      - pathType: Prefix
        path: /nginx/shwish-wish(/|$)(.*)
        backend:
          service:
            name: shwish-wish-service
            port:
              number: 8080
