## Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service-registry-deployment
  labels:
    app: eureka-service-registry
  namespace: kv-backend-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service-registry
  template:
    metadata:
      labels:
        app: eureka-service-registry
    spec:
      containers:
      - name: eureka-service-registry
        image: kaivalya461/eureka-service-registry


---
## Service       
apiVersion: v1
kind: Service
metadata:
  name: eureka-service-registry-service
  namespace: kv-backend-apps
spec:
  selector:
    app: eureka-service-registry
  # type: LoadBalancer
  ports:
    - name: eureka-service-registry
      protocol: TCP
      port: 80
      targetPort: 8761


---
## Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eureka-service-registry-ingress
  namespace: kv-backend-apps
spec:
  ingressClassName: nginx
  rules:
  - host: "service-registry.kvhome.in"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: eureka-service-registry-service
            port:
              number: 80