apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  # namespace: default
spec:
  storageClassName: postgres-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi