#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: my-postgres-volume
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
      - name: postgres
        image: postgres
        imagePullPolicy: Never      
        env:
          - name: POSTGRES_PASSWORD
            value: "changeit"
        volumeMounts:
            #Data Mount for Postgres DB
          - name: my-postgres-volume
            subPath: "db-data"
            mountPath: "/var/lib/postgresql/data"


      

---
#Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  type: LoadBalancer  
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
      # nodePort: 30030        