apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  type: LoadBalancer  
  ports:
    - name: postgres
      protocol: TCP
      port: 8080
      targetPort: 8080
      # nodePort: 30030