apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: postgres-data
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    ## Update below path with appropriate host path ##
    
    # Linux Path
    # path: "/home/pvtest"

    # Truenas Dataset
    # /mnt/pool_32_gig/truenas-docker-apps/DockerDataVolume/Postgress
    path: "/mnt/pool_32_gig/truenas-docker-apps/DockerDataVolume/Postgress"

    # Windows Path
    # path: "F:\\DatabaseStorage\\KubernetesPVData\\postgres-pv"